name: pleasant
description: In pursuit of beautiful pleasant code like `3.times {}`.
version: 0.0.1-dev
repository: https://github.com/0xharkirat/pleasant

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  characters: ^1.4.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
